name: SelviytymisHarpake
version: '1.20'
main: net.gahvila.selviytymisharpake.SelviytymisHarpake
description: Lisäosa Gahvilan survival palvelimelle.
api-version: '1.20'
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    #needed for sethome
    NoteBlockAPI:
      required: false
    CarbonChat:
      required: false
      join-classpath: true
