name: survival
version: '1.21'
main: net.gahvila.survival.survival
description: Lisäosa Gahvilan survival palvelimelle.
api-version: '1.21'
dependencies:
  server:
    GahvilaCore:
      required: true
      load: BEFORE
    JakesRTP:
      load: AFTER
      required: true
    #needed for sethome
    NoteBlockAPI:
      required: false
    CarbonChat:
      required: false
      join-classpath: true
    CrashClaim:
      required: true
      join-classpath: true
