name: survival
version: '${version}'
main: net.gahvila.survival.survival
description: Lisäosa Gahvilan survival palvelimelle.
api-version: '1.21'
dependencies:
  server:
    GahvilaCore:
      required: true
      load: BEFORE
    #needed for sethome
    NoteBlockAPI:
      required: false
    CarbonChat:
      required: false
      join-classpath: true
    CrashClaim:
      required: false
      join-classpath: true
