name: SelviytymisHarpake
version: 1.20
main: net.gahvila.selviytymisharpake.SelviytymisHarpake
api-version: 1.20
authors: [ Jokni ]
depend: [ Vault ]
description: Lisäosa Gahvilan survival palvelimelle.
commands:
  kauppa:
  resurssinether:
  editwarp:
  delwarp:
  warp:
  buywarp:
  setwarp:

